/*
    Auto-generated by eccles-tts-packager. DO NOT EDIT.
    This file indexes the StaticModel.eccles binary bundle.
    Include this file in your firmware to address clips by name.
*/

#ifndef ECCLES_STATIC_MODEL_INDEX
#define ECCLES_STATIC_MODEL_INDEX

#include "EcclesTypes.h"

//audio format shared by all clips in this bundle
ECCLES_API {

    static const e_uint32 ECCLES_SAMPLE_RATE = 8000;
    static const e_uint16 ECCLES_BIT_DEPTH   = 16;
    static const e_uint16 ECCLES_CHANNELS    = 1;

    //struct representation of one packaged audio clip inside the model bundle
    typedef struct {
        e_string name;   //clip name,extension stripped,used as the fromText() lookup key
        e_uint32 offset; //byte offset of this clip inside the .eccles binary
        e_uint32 size;   //byte size of this clip's audio payload
    } model_t;

};

ECCLES_API {

    model_t AND = {
        .name   = "and",
        .offset = 6U,
        .size   = 5728U
    };

    model_t BLUETOOTH = {
        .name   = "bluetooth",
        .offset = 5734U,
        .size   = 9564U
    };

    model_t D11 = {
        .name   = "d11",
        .offset = 15298U,
        .size   = 7850U
    };

    model_t D15 = {
        .name   = "d15",
        .offset = 23148U,
        .size   = 11844U
    };

    model_t D18 = {
        .name   = "d18",
        .offset = 34992U,
        .size   = 9700U
    };

    model_t D5 = {
        .name   = "d5",
        .offset = 44692U,
        .size   = 8876U
    };

    model_t D50 = {
        .name   = "d50",
        .offset = 53568U,
        .size   = 9294U
    };

    model_t D8 = {
        .name   = "d8",
        .offset = 62862U,
        .size   = 5690U
    };

    model_t ECCLES = {
        .name   = "eccles",
        .offset = 68552U,
        .size   = 10660U
    };

    model_t ECCLESIASTES = {
        .name   = "ecclesiastes",
        .offset = 79212U,
        .size   = 18302U
    };

    model_t ENGINE = {
        .name   = "engine",
        .offset = 97514U,
        .size   = 7482U
    };

    model_t FAILED = {
        .name   = "failed",
        .offset = 104996U,
        .size   = 8794U
    };

    //returns the model_t whose name matches the given text,e.g fromText("hello")
    //returns a zeroed model_t with name = nullptr if no match is found
    model_t fromText(e_string text){
        e_uint32 hash = eccles_hashRT(text);
        switch(hash){
            case 193486360U: return AND; //and
            case 1475233723U: return BLUETOOTH; //bluetooth
            case 193487563U: return D11; //d11
            case 193487567U: return D15; //d15
            case 193487570U: return D18; //d18
            case 5863262U: return D5; //d5
            case 193487694U: return D50; //d50
            case 5863265U: return D8; //d8
            case 4205815956U: return ECCLES; //eccles
            case 3062023421U: return ECCLESIASTES; //ecclesiastes
            case 4219001851U: return ENGINE; //engine
            case 4242795114U: return FAILED; //failed
            default: return {nullptr,0,0}; //no match found
        }
    }

};

#endif // ECCLES_STATIC_MODEL_INDEX
