//base implementation of the static model packager

#include "staticModel.h"
#include "WavFile.h"
#include "AudioConfig.h"
#include <iostream>
#include <filesystem>
#include <fstream>
#include <cstdlib>
#include <cstring>
#include <cctype>
#include <vector>
#include <string>
#include <algorithm>

ECCLES_API {

    using namespace std;
    namespace fs = std::filesystem;

    //helper class for cpp header source code generation
    //generates a .h file that acts as a compile-time index into the .eccles binary model,
    //the firmware includes this header to know each clip's name,offset and size
    class SourceCodeWriter {

        ofstream file; //underlying output header file

        //internal record of one collected model entry,buffered until close() so fromText() can be built
        struct Entry {
            e_strings stem;     //uppercase stem e.g "HELLO" — used as variable name and case label
            e_strings name;     //lowercase stem,extension stripped e.g "hello" — stored in model_t.name
                                //and used as the fromText() lookup key,so callers pass fromText("hello")
                                //instead of fromText("hello.wav")
            e_uint32  offset;   //byte offset of this clip inside the .eccles binary
            e_uint32  size;     //byte size of this clip's audio payload
        };

        vector<Entry> entries; //all collected entries,filled by writeModel(),consumed by close()

        //djb2 hash used internally by the packager at generation time to pre-compute
        //the constexpr case label values written into the generated switch
        static e_uint32 djb2(e_string s){
            e_uint32 hash = 5381;
            e_uint8  c;
            while((c = (e_uint8)*s++)) hash = ((hash << 5) + hash) + c;
            return hash;
        }

        //convert a filename stem to uppercase e.g "hello" -> "HELLO"
        static e_strings toUpper(e_strings s){
            transform(s.begin(),s.end(),s.begin(),::toupper);
            return s;
        }

        //strip the file extension from a filename e.g "hello.wav" -> "hello"
        static e_strings stripExt(const e_strings& filename){
            e_uint32 dot = (e_uint32)filename.rfind('.');
            if(dot == (e_uint32)e_strings::npos) return filename;
            return filename.substr(0,dot);
        }

        public:

        //creates and opens the source code file for writing,returns true on success
        e_boolean open(e_string path){
            file.open(path);
            if(!file){
                cerr<<"SourceCodeWriter: failed to open output header file: "<<path<<endl;
                return false;
            }

            //write the file preamble: banner,include guard,and required includes
            file << "/*\n";
            file << "    Auto-generated by eccles-tts-packager. DO NOT EDIT.\n";
            file << "    This file indexes the StaticModel.eccles binary bundle.\n";
            file << "    Include this file in your firmware to address clips by name.\n";
            file << "*/\n\n";
            file << "#ifndef ECCLES_STATIC_MODEL_INDEX\n";
            file << "#define ECCLES_STATIC_MODEL_INDEX\n\n";
            file << "#include \"EcclesTypes.h\"\n\n"; //brings in all e_ types and ECCLES_API

            return (e_boolean)file;
        }

        //write the shared wav format info as constants so the firmware knows
        //what format all clips in this bundle are encoded in,called once for the reference file
        void writeHeader(const wav_header_t& h){
            if(!file) return;
            file << "//audio format shared by all clips in this bundle\n";
            file << "ECCLES_API {\n\n";
            file << "    static const e_uint32 ECCLES_SAMPLE_RATE = " << h.sampleRate << ";\n";
            file << "    static const e_uint16 ECCLES_BIT_DEPTH   = " << h.bitDepth   << ";\n";
            file << "    static const e_uint16 ECCLES_CHANNELS    = " << h.channel    << ";\n\n";

            //define model_t using Eccles types — self-contained in this header
            //offset/size are e_uint32: ESP32 flash is at most a few tens of MB,well
            //within a 32 bit range,e_uint64 here would just waste RAM for no benefit
            file << "    //struct representation of one packaged audio clip inside the model bundle\n";
            file << "    typedef struct {\n";
            file << "        e_string name;   //clip name,extension stripped,used as the fromText() lookup key\n";
            file << "        e_uint32 offset; //byte offset of this clip inside the .eccles binary\n";
            file << "        e_uint32 size;   //byte size of this clip's audio payload\n";
            file << "    } model_t;\n\n";

            //eccles_hashCT (compile-time) and eccles_hashRT (runtime) are already provided by
            //EcclesTypes.h,which is included above,so we don't redefine them here — doing so
            //would give a duplicate definition error once this header and EcclesTypes.h are
            //both included by the firmware

            file << "};\n\n"; //close the ECCLES_API block for the header section
        }

        //buffer one model entry for later emission,the actual writing happens in close()
        //so that both the named instances and fromText() can be emitted together
        void writeModel(const model_t& m){
            if(!file) return;
            Entry e;
            e.name     = stripExt(m.name);          //"hello.wav" -> "hello",used for .name and fromText()
            e.stem     = toUpper(e.name);            //uppercase stem becomes the variable name,"hello" -> "HELLO"
            e.offset   = m.offset;
            e.size     = m.size;
            entries.push_back(e);
        }

        //emit all buffered entries as named model_t instances and the fromText() function,
        //then close the include guard and flush the file
        void close(){
            if(!file) return;

            //open the main ECCLES_API block that holds all the model instances and fromText()
            file << "ECCLES_API {\n\n";

            //emit one named model_t instance per clip
            //variable name is the uppercased stem: hello.wav -> model_t HELLO = { ... }
            for(const Entry& e : entries){
                file << "    model_t " << e.stem << " = {\n";
                file << "        .name   = \"" << e.name << "\",\n";
                file << "        .offset = " << e.offset << "U,\n";
                file << "        .size   = " << e.size   << "U\n";
                file << "    };\n\n";
            }

            //fromText() — takes a clip name (without extension,e.g "hello") and returns the
            //matching model_t,the switch dispatches on the runtime hash of the input
            //
            //NOTE: case labels are raw integer constants pre-computed by the packager's own
            //djb2() at pack time — no eccles_hashCT() calls in the generated code at all,
            //the firmware just sees plain integers like "case 2219287063:" which the compiler
            //treats as a constant and builds a jump table from,zero RAM,zero dependency on
            //the firmware's hash functions in the generated file itself
            file << "    //returns the model_t whose name matches the given text,e.g fromText(\"hello\")\n";
            file << "    //returns a zeroed model_t with name = nullptr if no match is found\n";
            file << "    model_t fromText(e_string text){\n";
            file << "        e_uint32 hash = eccles_hashRT(text);\n";
            file << "        switch(hash){\n";

            for(const Entry& e : entries){
                //hash the name at pack-time using the packager's own djb2(),the result is
                //the same value eccles_hashRT would produce at runtime for the same string
                //since both use the identical djb2 algorithm — emit it as a plain integer
                e_uint32 h = djb2(e.name.c_str());
                file << "            case " << h << "U: return " << e.stem << "; //" << e.name << "\n";
            }

            file << "            default: return {nullptr,0,0}; //no match found\n";
            file << "        }\n";
            file << "    }\n\n";

            file << "};\n\n"; //close the main ECCLES_API block

            file << "#endif // ECCLES_STATIC_MODEL_INDEX\n";
            file.close();
        }

    };

    //STATIC MODEL PACKAGING APIs

    //load and package all the wav files in eccles/resources if this runs from platformIO
    //or in the specified folder if it runs from the command prompt,returns true if everything went well
    e_boolean staticModel::pack(){
        //globals
        wav_header_t header;
        WavFile wf;
        AudioConfig config;

        e_string folder     = nullptr;
        e_string configFile = nullptr;

        e_string outP = nullptr; //path for the binary .eccles model file
        e_string outH = nullptr; //path for the generated .h index file

        SourceCodeWriter sw;

        //check if we are running on platformIO
        if(globalState.platformIO){
            //paths are relative to eccles/tools/bin/ where the packager runs from
            //IDF project layout: littlefs_image/ for the binary, components/eccles/include/ for the header
            folder     = "../../resources/models/";
            outP       = "../../../littlefs_image/StaticModel.eccles";
            outH       = "../../../components/eccles/include/StaticModel.h";
            configFile = "EcclesConfig.txt";
        } else {
            folder     = globalState.folderName;
            configFile = globalState.configPath;
            outP       = "StaticModel.eccles";
            outH       = "StaticModel.h";
        }

        //check if resource folder has been specified
        if(folder == nullptr){
            cerr<<"eccles-tts-packager: folder not specified"<<endl;
            return false;
        }
        //we can forgive config if it is not present,we will use the default eccles_config_t
        cout<<"eccles-tts-packager: packaging all wav files in the specified folder -> "<<folder<<endl;

        //first check if the folder even exists
        if(!fs::exists(folder)){
            cerr<<"eccles-tts-packager: the provided resource folder ->"<<folder<<" is not found please make sure the path is valid"<<endl;
            return false;
        }

        //check if the provided path is even a real folder
        if(!fs::is_directory(folder)){
            cerr<<"eccles-tts-packager: the provided resource folder ->"<<folder<<" is not a real folder exiting..."<<endl;
            return false;
        }

        //now we open the binary output model file
        if(!wf.open(outP,FileMode::WRITE)){
            cerr<<"eccles-tts-packager: failed to open the model file with the following path ->"<<outP<<endl;
            return false;
        }

        //now we open the config file,failure here is non-fatal,default config will be used
        if(!config.open(configFile)){
            //FIX: configFile is nullptr whenever no config .txt was supplied (the normal,
            //documented default case). Printing a null e_string via operator<< here used to
            //silently set cerr's failbit, which suppresses every subsequent cerr message for
            //the rest of this run -- so any real error further down (missing wav files,
            //failure to open the output header, etc) would then print nothing at all. Guard
            //against printing a null pointer instead.
            cerr<<"eccles-tts-packager: failed to open the config file provided with this path ->"
                <<(configFile ? configFile : "<none>")<<" default configurations will be applied"<<endl;
        }

        //now open the generated header file
        if(!sw.open(outH)){
            //no source code index means the firmware has no way to address the clips,stop work
            cerr<<"eccles-tts-packager: failed to open source code file with the following path ->"<<outH<<" exiting..."<<endl;
            return false;
        }

        //open the specified folder and scan all wav files
        e_uint32 wf_count = 0;
        e_boolean refFile = false; //we need a reference file to extract the shared format meta-data

        e_uint32 offset = 0; //running byte offset into the .eccles binary,written into the index for each clip

        //FIX: fs::directory_iterator's traversal order is filesystem/OS-dependent, not
        //alphabetical. That made both the on-disk clip order (and thus every clip's byte
        //offset) and, more importantly, which file becomes the format "reference" that others
        //are checked against, non-deterministic across machines/runs. Sorting first makes
        //packaging reproducible.
        vector<fs::path> wavPaths;
        for(const auto& wavEntry : fs::directory_iterator(folder)){
            wavPaths.push_back(wavEntry.path());
        }
        sort(wavPaths.begin(), wavPaths.end());

        for(const auto& wavPath : wavPaths){
            //FIX: extension comparison used to be case-sensitive, silently skipping any file
            //saved as ".WAV" (common from Windows recording tools) with no warning at all.
            string ext = wavPath.extension().string();
            for(auto& c : ext) c = (char) tolower((unsigned char) c);
            if(ext == ".wav"){ //here we got a wav file,lets process it

                //now we create a wav file for each wav file and read its entire content
                WavFile wfs;
                string wpt_str = wavPath.string();
                e_string wpt   = wpt_str.c_str();

                if(!wfs.open(wpt,FileMode::READ)){
                    //we can't camouflage this,if a file fails to open we stop all processing
                    cerr<<"eccles-tts-packaging: the following file with path ->"<<wpt<<" failed to open"<<endl;
                    sw.close();
                    return false;
                }

                //get the total size of the opened file
                e_uint32 totalSize = wfs.getSize();

                //FIX: a file shorter than the wav header itself (corrupt/truncated) would
                //make the subtraction below underflow (unsigned) into a huge bogus size. In
                //practice verifyHeader()'s magic-byte check almost certainly rejects such a
                //file first, but this closes the gap explicitly instead of relying on that.
                if(totalSize < sizeof(wav_header_t)){
                    cerr<<"eccles-tts-packager: "<<wpt<<" is smaller than a wav header, skipping"<<endl;
                    continue;
                }

                //read the file header first and verify its actually a real wav
                wav_header_t head;
                wfs.readHeader(head);
                if(!wfs.verifyHeader(head)) continue; //not a real wav,skip it

                //the header was already consumed from the stream by readHeader,
                //so the remaining readable bytes are the audio payload only
                e_uint32 audioSize = totalSize - (e_uint32)sizeof(wav_header_t);

                //create a buffer sized to the audio payload
                e_uint8* fileBuffer = (e_uint8*) malloc(audioSize);
                if(!fileBuffer){
                    //how can this be
                    cerr<<"eccles-tts-packager: unable to allocate memory for wav processing,possibly out of memory"<<endl;
                    sw.close();
                    return false;
                }

                //read the audio payload into this buffer
                if(wfs.read(fileBuffer,audioSize) != audioSize){
                    //partial or corrupt read,we must stop work
                    free(fileBuffer);
                    cerr<<"eccles-tts-packager: unable to read the entire content of ->"<<wpt<<" possibly corrupt file"<<endl;
                    sw.close();
                    return false;
                }

                /*
                    now we configure this buffer with the provided configurations,NOTE: the actual wav header we are using
                    is the one provided by the config not by the file itself,the config modifies the actual wav header to match
                    whatever is actually modified by the config and the modified header is what we use here
                */
                vector<e_uint8> cfd = config.configure(fileBuffer,audioSize,head);

                //configure() always returns the processed buffer (possibly same data if nothing changed)
                //hand ownership to cfd and free the raw buffer we no longer need
                free(fileBuffer);
                fileBuffer = nullptr;

                //update the audio size to reflect whatever configure() produced
                e_uint32 size = (e_uint32)cfd.size();

                //check if reference file has been read
                if(!refFile){
                    //we ask the source code writer to write the shared format constants first
                    sw.writeHeader(head);

                    //write the ECCLES magic number as the very first thing in the binary model file
                    e_uint8 mHead[6] = {0x45,0x43,0x43,0x4C,0x45,0x53}; //ECCLES
                    if(!wf.write(mHead,6)){
                        //if the magic header failed to write everything else is rubbish so we quit anyway
                        cerr<<"eccles-tts-packager: failed to write model header"<<endl;
                        sw.close();
                        return false;
                    }

                    //set the header of the first file as the reference all other files must match
                    header  = head;
                    refFile = true;

                    //we must increment the offset to account for the magic header size
                    offset += 6;

                } else {
                    //we verify every other header against the reference,if any doesn't match
                    //the reference header we throw error and quit,all clips must share the same format
                    if(!WavFile::compareHeader(header,head)){
                        //we use the reference header as the universal header written to the
                        //source file,if any file doesn't match this header we reject it and throw error
                        cerr<<"eccles-tts-packager: the following file header -> "<<wpt<<" doesn't match the reference file header exiting..."<<endl;
                        sw.close();
                        return false;
                    }
                }

                //write the configured audio content of this clip into the binary model file
                if(!wf.write(cfd.data(),size)){
                    //failure to write any clip is dangerous,we can't tolerate it
                    cerr<<"eccles-tts-packager: failed to write the content of the file -> "<<wpt<<" to the model buffer"<<endl;
                    sw.close();
                    return false;
                }

                //we succeeded so we write its source index entry
                //keep the filename string alive until after writeModel since model_t holds a raw pointer
                string fname_str = wavPath.filename().string();
                model_t mt = {
                    .name   = fname_str.c_str(),
                    .offset = offset,
                    .size   = size
                };

                //buffer the entry inside SourceCodeWriter,fromText() is built at close() time
                sw.writeModel(mt);

                //increment the offset so the next clip's entry points past this one
                offset += size;
                wf_count++;
            }
        }

        sw.close();

        //FIX: this used to return true (success) even when wf_count was 0. In that case
        //writeHeader() (which emits ECCLES_SAMPLE_RATE/ECCLES_BIT_DEPTH/ECCLES_CHANNELS) is
        //only ever called once a reference file is found, so the generated StaticModel.h
        //would silently be missing those constants -- and the only symptom would be a
        //confusing "undeclared identifier" error much later when the firmware tries to
        //compile against it. Fail clearly here instead.
        if(wf_count == 0){
            cerr<<"eccles-tts-packager: no valid .wav files found in "<<folder<<", nothing was packaged"<<endl;
            return false;
        }

        cout<<"eccles-tts-packager: successfully packaged "<<wf_count<<" wav file(s)"<<endl;
        return true;
    }

    e_boolean staticModel::extract(){
        //extraction mode: not yet implemented
        return false;
    }

};
