//base implementation of the EcclesTTS engine
//PORT NOTE: pure C++ logic, no framework dependency, carried over unchanged

#include "EcclesTTS.h"
#include <cstring> //needed for the tokenizer
#include "StaticModel.h" //necessary for this api,generated by eccles-tts-packager.exe

ECCLES_API {
    //define the run flag
    e_boolean EcclesTTS::run = false;
    e_boolean EcclesTTS::valid = false;
    AUDIO_MODE EcclesTTS::mode = AUDIO_MODE::I2S_DAC; //default mode
    AudioOutput EcclesTTS::mp;

    //init tts engine this should be called before any tts operation should be called
    e_boolean EcclesTTS::initEngine(LANG lan){ //lang is reserved for future multi-lingual feature
        //check if we are already active
        if(valid) return true; //already running

        //alert this very important operation for debug use
        ECCLES_LOG_LINE("initializing the eccles tts engine");

        //initialize the audio pipeline
        audioConfig cfg;
        cfg.sampleSize = ECCLES_BIT_DEPTH;
        cfg.sampleRate = ECCLES_SAMPLE_RATE;
        cfg.channel = (ECCLES_CHANNELS == 1) ? AUDIO_CHANNEL::MONO : AUDIO_CHANNEL::STEREO;
        
        mp.start(cfg);

        //load the staticModel.eccles file into our audio pipeline
        if(!mp.load("StaticModel.eccles")){
            ECCLES_LOG_LINE("failed to open StaticModel.eccles needed by the tts system");
            //close the audioThread
            audioTask t;
            t.type = AUDIO_TYPE::SHUTDOWN;
            mp.play(t); 
            return false;
        }
        //tts is in charge now set the Audio delay to 0
        AudioOutput::delay = 0;

        return (run = valid = true);
    }

    //pause the tts system
    void EcclesTTS::pause(){
        //return the audio output delay to the defaut
        AudioOutput::delay = AUDIO_OUTPUT_DEFAULT_DELAY;
        run = false;
    }

    //continue the tts engine after it is paused
    void EcclesTTS::play(){
        AudioOutput::delay = 0; //tts over delay per clip
        run = true;
    }

    //change the current tts play mode
    void EcclesTTS::setMode(AUDIO_MODE m){
        if((m != AUDIO_MODE::I2S) && (m != AUDIO_MODE::I2S_DAC)) return; //invalid mode use the default mode
        mode = m;
    }

    //get the current tts play mode
    AUDIO_MODE EcclesTTS::getMode(){
        return mode;
    }

    //the main concept, play the actual tts texts
    void EcclesTTS::speak(e_string cwords){
        //check if we are not paused and that the audio player is valid
        if((!run) || (!valid) || (!cwords)) return;

        ECCLES_LOG("eccles-tts speaking: ");
        ECCLES_LOG_LINE(cwords);
        
        //check if the supplied words is in range
        if(strlen(cwords) >= 128){
            ECCLES_LOG_LINE("sentence longer than 128 are not yet supported tts.speak aborted");
            return;
        }

        //we needed to convert the arg to a modifiable char for strtok to work
        e_char words[128];
        memcpy(words,cwords,strlen(cwords) + 1);

        //split the provided text and get it one by one and call the audio api to play it
        e_string word = strtok(words," "); //split the sentence word by word

        while(word != nullptr){
            //check if this word is an integer, NOTE: atoi will return 0 on a normal word,atoi('hello') gives us 0 so we use this to detect when normal words are given
            //FIX: this used to narrow atoi's full int result into e_uint8 *before* the >100
            //range check, so e.g. "300" truncated to 44 and passed the check, causing the
            //device to speak the wrong number instead of rejecting it. Range-check first.
            e_int fullValue = atoi(word);
            if(fullValue > 0 || eccles_compareString(word,"0")){ //we got an integer,there case is different
                //we check if this integer is in the 100 range, we currently support playing 1 - 100
                if(fullValue > 100 || fullValue < 0) {
                    ECCLES_LOG_LINE("speaking of integers above 100 is currently not supported the value is discarded...");
                } else {
                    playDigits((e_uint8) fullValue);
                }
            } else { //not an integer, a normal phrase
                //get the model representation of this word
                model_t mt = fromText(word);
                if(mt.name == nullptr){
                    //the word is not present in the loaded model lists how do we handle this
                    //continue playing a sentence that lacks a word will make no meaning so we stop 
                    //playing any sentence that preceeds this 
                    break;
                } else { //this word is part of our model package
                    audioClip ac;
                    ac.offset = mt.offset;
                    ac.size = mt.size;
                    ac.delay = 500;  //we give a half a second delay for each word so that the entire sentence should appear natural

                    mp.play(ac,mode); //i2s dac is default for now
                }
            }
            word = strtok(nullptr," ");
        }
        
    }

    //speak a voice buffer using the tts system
    void EcclesTTS::speakBuffer(e_uint8* buffer,e_uint32 size){
        //check arg validity
        if(!run || buffer == nullptr || size == 0) return;// invalid args
        mp.playBuffer(buffer,size,mode);
    }

    //play digits using the tts play engine
    void EcclesTTS::playDigits(e_uint8 d){
        //we get the digits hundred,tens and unit since in the model we represent
        //numeric values like that and while playing then we build them back together

        e_uint8 h = d/100;
        e_uint8 t = (d / 10) % 10;
        e_uint8 u = d % 10;

        

        //for the digitPlayer to be able to play digits fastest we need to construct the digit name
        //from the digits itself but we found a bug in the packager generated header because the name of the model
        //is actually the name of the file hence 5.wav translate to model_t 5,
        //all thanks to my friend daniel who pointed this out so we prefix every numeric clip
        //with d first letter of daniel my frient to give this credit to him
        


        //play the hundred
        if(h > 0){
            //if it's a hundred we add 00 hundreds are represented as 100,
            e_char hdc[5];
            hdc[0] = 'd';
            hdc[1] = (e_char) h + 48; //convert to the ascii equiv
            hdc[2] = (e_char) 48; //0
            hdc[3] = (e_char) 48; //0
            hdc[4] = '\0';

            model_t mt = fromText(hdc);//note digit names in model resources must be there value not name you should not use one for 1 so that it can be found instead use d1.wav not one.wav
            if(mt.name == nullptr){
                //damn digit not found we discard everything
                return;
            }
            audioClip cl;
            cl.offset = mt.offset;
            cl.size = mt.size;
            if(t == 0 && u == 0) cl.delay = 500; //the last clip should be delayed so it does'nt jam the next sentence
            mp.play(cl,mode);

            if(t == 0 and u == 0) return; //no more job

            //in the hundred mode we needed to add the and so it sounds 'hundred and' natural
            model_t mat = fromText("and");
            if(mat.name == nullptr){
                //discard the rest since it will make no sense when played though
                return;
            }
            audioClip clp;
            clp.offset = mat.offset;
            clp.size = mat.size;
            mp.play(clp,mode);
        }

        //play the tens NOTE: under 20 tens is played together with its unit
        //because there is no accurately play teens digits,how can we play eleven or thirthen 
        //separately
        if(t > 0){ //here we got tens
            //if its a tens we add 0 because tens are represented as 20 , 50
            e_char dcc[4];
            dcc[0] = 'd';
            dcc[3] = '\0';

            //check if its a teen digit
            if(t < 2){ //get the full teens
                dcc[1] = (e_char) t + 48;
                dcc[2] = (e_char) u + 48;

                model_t mtt = fromText(dcc);
                if(mtt.name == nullptr) return; //exit everything else
                audioClip clpp;
                clpp.offset = mtt.offset;
                clpp.size = mtt.size;
                clpp.delay = 500;
                mp.play(clpp,mode);
                return;
            } 

            dcc[1] = (e_char) t + 48;
            dcc[2] = (e_char) 48; //0
            model_t mtt = fromText(dcc);
            if(mtt.name == nullptr) return; //exit everything else
            audioClip clpp;
            clpp.offset = mtt.offset;
            clpp.size = mtt.size;
            clpp.delay = (u == 0) ? 500 : 0;
            mp.play(clpp,mode);

            if(u == 0) return; //no more work
        }

        //play unit
        //if we get here play anything find in the unit block regardless
        e_char dc[3];
        dc[0] = 'd';
        dc[1] = (e_char) u + 48;
        dc[2] = '\0';
            
        model_t mmt = fromText(dc);
        if(mmt.name != nullptr){
            audioClip cclp;
            cclp.offset = mmt.offset;
            cclp.size = mmt.size;
            cclp.delay = 500;
            mp.play(cclp,mode);
        }
        
    }

    //get the underlying media player for other audio tasks
    AudioOutput* EcclesTTS::getOutput(){
        if(run) return nullptr; //pause the tts first
        return &mp; //the media player
    }

    //resets the tts system
    void EcclesTTS::reset(){
        audioConfig cfg;
        cfg.sampleSize = ECCLES_BIT_DEPTH;
        cfg.sampleRate = ECCLES_SAMPLE_RATE;
        cfg.channel = (ECCLES_CHANNELS == 1) ? AUDIO_CHANNEL::MONO : AUDIO_CHANNEL::STEREO;
        mp.reConfigure(cfg,mode);
        play();
    }

};
